### ISSUE TITLE
Allow for different rout pattern generation

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCms#15]
The current route generation uses the `AlPageManager::slugify` for both the pagename and permalink.
This can give some problems when converting a old to a new site. It seems like it is currently not possible to have routes like '/en/test' or '/mycompany/about'. 

I think adding a way to better manage urls and/or page would be a feature needed for people to start using RedKiteCms.
What are the ideas on this?

This issue maybe related to  #6

**Comment by janxin** [comment]
No more appliable
