### ISSUE TITLE
Add Page redirect management

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCms#16]
When porting a CMS to Redkite url's need to be remapped/redirected to new url's.
Currently there is no place to do this and this should be added (in my opinion). 

Also when changing published page/seo permalink support should be added to auto generate permanent redirect for these pages.

I will probably start work on this next week but please let me know if you are already working on this or if you have a better idea.

**Comment by janxin** [comment]
No more appliable
