### ISSUE TITLE
Database with no pages gives fatal exception.

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCms#17]
If you remove all rows from `al_page` and go to `/backend/login` you will see the following exception:
`FatalErrorException: Error: Call to a member function getPageName() on a non-object in /vagrant/vendor/redkite-cms/redkite-cms-bundle/RedKiteLabs/RedKiteCmsBundle/Controller/SecurityController.php line 62`

I expect that this is not meant to happen a quick fix would be to just add a homepage is there is none or even better tell the user and force him to create one.

**Comment by janxin** [comment]
No more appliable
