### ISSUE TITLE
Add deploy revision and rollback support

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCms#19]
Currently there is no way to restore the editor/work environment to the state that the live or stage environment is in, It would be nice to have a rollback to last deployed version staging or live environment.

On a user interface note maybe it would be a idea to combine the deploy to stage and deploy to production button into one deploy button where people can those which revision to deploy to which environment. 
For example be able to say deploy 'stage' to 'production' or deploy 'working' to 'stage'.

What are your thoughts on this?

**Comment by janxin** [comment]
No more appliable
