### ISSUE TITLE
Rework the resource locking

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCms#28]
Currently the resource locking is based per url. 
This seems a incorrect and very unfriendly way of working with this. 

I propose to rework the locking mechanism to be handled on a resource.
And to rework the interface to show a locked resource as read only.

This will also remove the very nasty `The resource you requested is locked by another user. Please retry in a couple of minutes` error page.

**Comment by janxin** [comment]
No more appliable
