### ISSUE TITLE
Just fresh install

### ISSUE THREAD

**Issue by marcoooo** [redkite-labs/RedKiteCms#78]
Hi All, first thnxs for this tool :-)
Juste freshly installed redkite from my fork, install went ok, but I have a message when opening media manager.
"Invalid backend configuration.
Readable volumes not available.
"
FI : I a under windows, wamp and I doubt having file permission issues. (My deployment will be on linux hopefully).

I didn't find any way to configure ElFinder to work (as it returns this message from this page "backend/en/al_elFinderMediaConnect?cmd=open&target=&init=1&tree=1&_=1396134653751" 
["Driver \"elFinderVolumeLocalFileSystem\" : Root folder does not exists."]}

thnxs for your help.

**Comment by janxin** [comment]
@marcoooo sorry for late reply. Today RedKite CMS 1 is deprecated: could you try the new one https://github.com/redkite-labs/RedKiteCms and open a new issue if the problem still persiste for you?

**Comment by marcoooo** [comment]
thanxs for your response :p I'll check out the new version !

Regards.
