### ISSUE TITLE
Fresh Install 404 page

### ISSUE THREAD

**Issue by marcoooo** [redkite-labs/RedKiteCms#79]
Hi, just come from RedKite 1.1 to 2.0, freshly installted from composer, unfortunatly I got a 404 page when running my wirtualhost. 

I checked files generated during 'install' process (I mean my web.site.fr direcotry and json files automatic creation). But file contents were all empty...

I checked this file RedKiteCms\Tools\FilesystemTools and I saw something weird in "writeFile" function : when you try to lock file, and then want to write in it, you use file_put_contents, which is by mean a short cut to 'fopen/fwrite/fclose', so I understood why generated file where empty (file put content can't write in file if you just locked it few lines before). I changed the file put content to a standard fwrite, the content was then well written. 

Unfortunatly, it didn't resolve my 404 problem :-(.

I Juste made a fork and push my 'correction', tell me if it worth a pull !

**Comment by janxin** [comment]
Hi,
that was a mistake with the install document: just go to http://your.domain/login. The 404 page is because any page has been published yet. Let me know if that works. 

Obviously you can send the pull request as well.
